on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kurniadi2271/markdownlint-cli2-action@v11
      with:
        globs: |
          *.md
          !test/*.md
